### ISSUE TITLE
Why escape colon and equals?

### ISSUE THREAD

**Issue by onlyanegg** [jwodder/javaproperties#3]
Hi. I'm wondering why you chose to escape colons and equals signs. I've read through a [couple](https://en.wikipedia.org/wiki/.properties) [references](https://docs.oracle.com/cd/E23095_01/Platform.93/ATGProgGuide/html/s0204propertiesfileformat01.html), and haven't seen anything saying that it's required or even acceptable. Is it valid for properties files?

Thanks :)

**Comment by jwodder** [comment]
The library's `dumps()` function mimics the behavior of `java.util.Properties`'s `store()` method, [whose documentation states in part](https://docs.oracle.com/javase/10/docs/api/java/util/Properties.html#store(java.io.Writer,java.lang.String)):

> The key and element characters #, !, =, and : are written with a preceding backslash to ensure that they are properly loaded.

I don't believe this is actually required for proper loading, but I do it anyway in order to match Java's behavior.  Escaping arbitrary characters in this way is acceptable, as, [to quote the documentation for the `load()` method](https://docs.oracle.com/javase/10/docs/api/java/util/Properties.html#load(java.io.Reader)):

> The method does not treat a backslash character, `\`, before a non-valid escape character as an error; the backslash is silently dropped. For example, in a Java string the sequence `"\z"` would cause a compile time error. In contrast, this method silently drops the backslash. Therefore, this method treats the two character sequence `"\b"` as equivalent to the single character `'b'`.

So `\=` in an element is equivalent to `=`.

**Comment by onlyanegg** [comment]
Thanks, @jwodder :)
